### PR TITLE
Feature/serialize custom errors

### PR DESCRIPTION
**Pull request by padilo**
Now the errors are serialized when the route is not serializable.

### CODE REVIEW

**Comment by padilo** [comment]
There are some missing parts still, do not merge but feel free to take a look ;)

**Comment by padilo** [comment]
Done, now ErrorHandler handles error non-serializable routes

**Comment by ruben-perez** [comment]
:+1:

**Comment by ramonibz** [comment]
:+1:

**Comment by padilo** [comment]
This doesn't have any sense right now, we don't use karyon anymore

**Pull request closed without merging**
