### PR TITLE
Fix endpoint precedence

### PR DESCRIPTION
**Pull request by enriclluelles**
Fixes the precedence between two endpoints that could handle a request as shown in the failing test

As we discussed previously, I researched how the best suited annotated method for handling a request is chosen in spring-webmvc. There its done matching the request against every single route defined that could handle it.

Here, I went the other way(since I think it's simpler and more performant), and like the `SimpleRouter` does, it goes with the first one that matches. So, almost all of the logic changed is the one performed at the module initialization, where it gets all the relevant annotations and inserts them.
Before all that I just performed a double sorting so they get inserted in an order that gets the precedence right. We still get the simplicity  and predictability of the simpleRouter but with the added convenience

### CODE REVIEW

**Comment by rogersole** [comment]
Looks great to me!

**Comment by victuxbb** [comment]
Well, first of all thanks for taking time to help me, really apreciate it!
In general, great job man! you fixed the problem and refactor a lot of things in a functional way :+1: 

The first commit about gitignore, really I don't know if its a good practice to put this kind of files on it, when I started the project I was reading about a global gitignore and how you really should use .gitignore.

https://help.github.com/articles/ignoring-files/#create-a-global-gitignore

So, when you have time tell me something about the comments and I will merge this PR.

Thanks again!

**Comment by enriclluelles** [comment]
A global gitignore is just a fail-safe that you individually set to, regardless of the .gitignore files on the projects you work on, not commit very usual files that don't need to.
But still, I think it's a lot better to have .gitignores per project, as you cannot enforce a global from a project and can't control what other people have or have not in their global one

**Comment by fiunchinho** [comment]
I normally prefer the global .gitignore for IDE related stuff. But I'm open to change my mind about it :dancer:

**Comment by victuxbb** [comment]
After talking about, its fine for me! let's merge :+1:

**Pull request merged**
