### PR TITLE
Hotfix/configuration not mandatory

### PR DESCRIPTION
**Pull request by padilo**
Configuration is not mandatory now, also added some logs to see which routes are registered.

### CODE REVIEW

**Comment by padilo** [comment]
This completely solves #20 and #21

**Comment by aramirez-es** [comment]
Thanks @padilo, I'm going to check it out :dancer:

**Comment by padilo** [comment]
Seems that the routes are not available when it starts the server, but in fact the server is not able to respond until the configuration is complete. I think there is still something wrong, not sure where but at least now works without a 404 when it's not 100% up and running.

**Comment by padilo** [comment]
And also #18 :)

**Comment by aramirez-es** [comment]
Tested that configuration is not mandatory now, so it solves #18.
But #20 and #21 still happen. We can double check this together if you want @padilo.

**Comment by padilo** [comment]
#21 is solved but It needs the part that is missing in #23, Now is rebased with master to be able to see it, take another look.
#20 I tested one more time, and It should be solved, as I said it creates the endpoints after the initialization, but It pauses all the requests until is initialized.
Previous versions of karyon-rest-router works in the same way, so the 404 shouldn't appear. If you see in any case that the 404 appear take a look at the logs of the application, because now you will see the routes registered and maybe is just that #23 is not part of this branch, now that is merged with master that comes with #23 you should see is working perfectly with your pta configuration.

Maybe I said too early that #20 and #21 is solved, because without #23 with your pta configuration, that there isn't a package configured to be scanned no route will be configured.

As I said now that is rebased all should work :)

**Comment by fiunchinho** [comment]
I'm merging this to move forward the issue. Let's all keep an eye to see if everything works. Thank you both @padilo and @aramirez-es

**Pull request merged**
