### PR TITLE
Corrected problem with test + empty package patch

### PR DESCRIPTION
**Pull request by padilo**
Corrects a problem with tests
Now if the property 'com.scmspain.karyon.rest.property.packages' it still search for Endpoints in all packages.
This behavior was broken in 1.3.1, when we introduced the multipackage endpoint configuration.

### CODE REVIEW

**Comment by padilo** [comment]
@aramirez-es this should fix the tests broken in #22

**Comment by padilo** [comment]
It also resolves #20 and #21

**Comment by aramirez-es** [comment]
Hey @padilo thanks for working on this!

I did some tests with the following results:
- It **fixes tests broken in #22** as you said, but:
- #20 remains happening.
- #21 just works if I apply the modifications you pointed out here https://github.com/scm-spain/pta-adinsertion/pull/158

Maybe it's me, so when can talk about this tomorrow.

**Comment by padilo** [comment]
**#20 - Partially solved**
Seems to be partially solved but not at all, I'm going to solve it completely in another PR as I will add some logging to see all the endpoint registered in Karyon, that should help a lot :).

Previously if you didn't set the list of package to scan it doesn't register Endpoints, now it does, so it should work properly now. But... Karyon may be started without all endpoints registered until he finish to scan packages. The way you are doing the integration tests in scm-spain/pta-adinsertion it shouldn't be a problem, so I think the way it works now it works but still can be improved to work the same as older versions.

**#21 - Partially solved**
Works, but still needs the workaround of configuration which at least now this is not a stopper. I will change definitely correct this in another PR.

**#22 - Completely solved.**

----

BTW now the package scan property it's not required as it wasn't in older versions, but I think it should be set in all cases as the package scan is very costly and it slows down a lot the initialization of karyon-rest-router.

With this PR there are still some things to improve but at least there isn't a stopper now.

**Comment by aramirez-es** [comment]
Ok, let's merge to avoid tests failing in #22 and then wait for the other PR's you mentioned.
:+1:

**Comment by fiunchinho** [comment]
:+1:

**Pull request merged**
